リファクタリング
geekcamp-vol11-team30/frontend pull request #46
Opened 2023-09-24 19:34 UTC by xpadev-net

- eslintの設定の強化及びそれに伴う修正
- 掃除
- 依存関係の更新
- リファクタリング(hook化etc)

2023-09-27 00:14 UTC, Yuma-Satake requested changes
ビックバンリファクタありがとうございます😇
修正というより、記法について何点か質問してるので対応お願いします🤲

2023-09-27 00:14 UTC, Yuma-Satake commented on src/components/GuestPage/GuestPageBody.tsx
> +    void router.push("/");
voidで返り値を使わない事を明示的になるほど
勉強になります

2023-09-27 00:14 UTC, Yuma-Satake commented on src/libraries/typeGuard.ts
>      // TODO: これどーすんの
人類の原罪が残ったままなのが笑う

2023-09-27 00:14 UTC, Yuma-Satake commented on src/pages/preview.tsx
> +  position: "absolute" as const,
過去俺が書いたコードだけど、fixedでいい気がしてる

2023-09-27 00:14 UTC, Yuma-Satake commented on .eslintrc.json
> +    "simple-import-sort/imports": "error",
あんまりimportの順番の制御に綺麗になる以外の意味を感じないんだけど、私の知らない旨みを教えてほしいです

2023-09-27 00:21 UTC, xpadev-net commented on src/components/Button.tsx
> +export const Button = ({ text, isPrimary, onClick }: props) => {
ついてないやつとReact.FCなやつとFCなやつが混在してたのでまとめて消し飛ばしました
~~(というか書くのめんどい)~~

2023-09-27 00:24 UTC, xpadev-net commented on src/libraries/typeGuard.ts
>      // TODO: これどーすんの
これは何に使ってるのかよくわからなかったから放置
どうせリファクタリングで使われなくなるからその時に消せばいいかなと

2023-09-27 00:25 UTC, xpadev-net commented on src/pages/preview.tsx
> +  position: "absolute" as const,
"absolute" as "absolute"が気持ち悪かっただけなので内容は任せます

2023-09-27 00:29 UTC, xpadev-net commented on .eslintrc.json
> +    "simple-import-sort/imports": "error",
同じパッケージからのimportが複数あったりしたので入れました
特に深い意味はないです

2023-09-27 00:36 UTC, Yuma-Satake commented on src/components/Button.tsx
> +export const Button = ({ text, isPrimary, onClick }: props) => {
@Yuta123456 
宗教戦争ですがどちらがお好みですか？

2023-09-27 00:36 UTC, Yuma-Satake commented on src/pages/preview.tsx
> +  position: "absolute" as const,
私がこのPRの後で直しときます罪

2023-09-27 00:37 UTC, Yuma-Satake commented on .eslintrc.json
> +    "simple-import-sort/imports": "error",
確かにimportはできるだけマージしたいお気持ち
確かにそれあるからあった方がいいのかなぁ

2023-09-30 07:31 UTC, Yuta123456 commented on src/components/Button.tsx
> +export const Button = ({ text, isPrimary, onClick }: props) => {
まず、`React.FC`は論外です。つけないか、`FC`なら僕は必ずつけます。
eslintのルールにもよりますが、関数の引数と返り値の型を必ず明示しなきゃいけないルールが存在して、インターン先とかでは大抵そのルールがありました。もしそのルール下だと、

```
export const Button: ({~~}: props): JSX.Elements = ({ text, isPrimary, onClick }: props) => {
```
みたいに型付けする必要があり、そしたら
```
export const Button: FC<props> = ({ text, isPrimary, onClick }) => {
```
って書きたいな。って感じです。（FCのシグネチャ（？）のお陰）
でもそのルール導入しないんならどっちでもいいです。書くのがめんどくさいとは思わないです。

2023-09-30 07:32 UTC, Yuta123456 commented on src/components/Button.tsx
> +type props = {
型は大文字が良いですね、めんどくさいって言われたらそれまでなんですが、、、読みやすさ的には

2023-09-30 07:34 UTC, Yuta123456 commented on src/libraries/typeGuard.ts
>      // TODO: これどーすんの
> これは何に使ってるのかよくわからなかったから放置
どうせリファクタリングで使われなくなるからその時に消せばいいかなと
これは、
`HourOfDay: (v: number): v is IHourOfDay =>`
に関する言及ですか？

2023-09-30 07:38 UTC, Yuta123456 commented on src/libraries/typeGuard.ts
>      // TODO: これどーすんの
TODOの部分は、
`(HourOfDay as unknown as number[])`の部分についての言及です。
1~24までの整数かどうかを判別するときに、`IHourOfDay`型の配列に対して `includes`メソッドを呼ぶと、引数が `IHourOfDay`型しか取れないんですよね。そうすると、例えば48とかが来た時に弾くためのメソッドなのに、`IHourOfDay`に対してしか呼べないのは意味わからないので、`IHourOfDay`型の配列を `number`にキャストしてあげる必要があるのですが、これをキャストするために一旦 `unknown`を経由しないとキャストできなくてしんどいなー。TODOで。って感じです。

2023-09-30 07:44 UTC, xpadev-net commented on src/components/Button.tsx
> +export const Button = ({ text, isPrimary, onClick }: props) => {
> eslintのルールにもよりますが、関数の引数と返り値の型を必ず明示しなきゃいけないルールが存在して、インターン先とかでは大抵そのルールがありました。

特に深い意味はないのでFCありにしてルールも入れますか〜

2023-09-30 07:44 UTC, xpadev-net commented on src/components/Button.tsx
> +type props = {
> 型は大文字が良いですね、めんどくさいって言われたらそれまでなんですが、、、読みやすさ的には

特に意味はないのでPropsにしちゃいますね

2023-09-30 07:47 UTC, xpadev-net commented on src/libraries/typeGuard.ts
>      // TODO: これどーすんの
了解です〜

2023-09-30 08:22 UTC, merged